# Generated by Django 6.0.4 on 2026-04-22 07:26

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medium', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcomment',
            name='blog',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='blog_comments', to='medium.blog'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='verificationcode',
            name='code',
            field=models.CharField(default=677644, max_length=6),
        ),
        migrations.AlterField(
            model_name='verificationcode',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2026, 4, 23, 7, 26, 42, 688329)),
        ),
    ]
