# Generated by Django 6.0.4 on 2026-05-13 08:56

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medium', '0002_blogcomment_blog_alter_verificationcode_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcomment',
            name='status',
            field=models.CharField(default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='blog',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='blog',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_blogs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='verificationcode',
            name='code',
            field=models.CharField(default=896802, max_length=6),
        ),
        migrations.AlterField(
            model_name='verificationcode',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2026, 5, 14, 8, 56, 31, 207287)),
        ),
    ]
